package com.elephant.notify.entity.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseNotifyUser<M extends BaseNotifyUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Long id) {
		set("id", id);
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public void setElaAddress(java.lang.String elaAddress) {
		set("ela_address", elaAddress);
	}
	
	public java.lang.String getElaAddress() {
		return getStr("ela_address");
	}

	public void setStatus(java.lang.Integer status) {
		set("status", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("status");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("email");
	}

	public void setLocalSystemTime(java.util.Date localSystemTime) {
		set("local_system_time", localSystemTime);
	}
	
	public java.util.Date getLocalSystemTime() {
		return get("local_system_time");
	}

	public void setVerifyCode(java.lang.String verifyCode) {
		set("verify_code", verifyCode);
	}
	
	public java.lang.String getVerifyCode() {
		return getStr("verify_code");
	}

	public void setUuid(java.lang.String uuid) {
		set("uuid", uuid);
	}
	
	public java.lang.String getUuid() {
		return getStr("uuid");
	}

}
