package com.elephant.notify.entity;

import com.elephant.notify.entity.base.BaseNotifyUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class NotifyUser extends BaseNotifyUser<NotifyUser> {
	public static final NotifyUser dao = new NotifyUser().dao();
}
